# SPDX-FileCopyrightText: 2024 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH, Darmstadt, Germany
#
# SPDX-License-Identifier: LGPL-3.0-or-later

name: Check AUTHORS and CONTRIBUTORS in metadata

on:
  push:
    paths:
    - AUTHORS
    - CONTRIBUTORS
    - .zenodo.json
  pull_request:
    paths:
    - AUTHORS
    - CONTRIBUTORS
    - .zenodo.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Try updating metadata
        run: python meta_update.py
      - name: Check for Updates
        run: git diff --exit-code
